/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class ClaimContract extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): ClaimContract;
  methods: {
    balances(arg0: string): TransactionObject<string>;

    getPublicKeyFromBitcoinSignature(
      hashValue: string | number[],
      r: string | number[],
      s: string | number[],
      v: number | string
    ): TransactionObject<string>;

    isValid(): TransactionObject<boolean>;

    testECRecover(): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
